name: Deploy to Cloud Run

on:
  push:
    branches:
      - staging

permissions:
    contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      - name: Build & Push Image
        env:
            IMAGE: us-west1-docker.pkg.dev/furwoodd-775d1/ntentan/api:${{ github.sha }}
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        env: 
            IMAGE: us-west1-docker.pkg.dev/furwoodd-775d1/ntentan/api:${{ github.sha }}
        run: |

          set -euo pipefail

          RAW_ENV=$(gcloud secrets versions access latest --secret=ntentan-api-env --project=furwoodd-775d1)
   
          if [ -z "$RAW_ENV" ]; then
            ENV_VARS="NODE_ENV=PRODUCTION"
          else
            ENV_VARS=$(printf "%s" "$RAW_ENV" | tr '\n' ',' | sed 's/,$//')

            ENV_VARS=$(printf "%s" "$ENV_VARS" | sed -E 's/(^|,)NODE_ENV=[^,]*(,|$)/\1\2/g' | sed 's/,,/,/g' | sed 's/^,//' | sed 's/,$//')
            ENV_VARS="${ENV_VARS},NODE_ENV=PRODUCTION"
          fi

          SERVICE_ACCOUNT="ntentan-temp@furwoodd-775d1.iam.gserviceaccount.com"

          gcloud run deploy ntentan-api \
            --image="$IMAGE" \
            --region=us-west1 \
            --platform=managed \
            --allow-unauthenticated \
            --update-env-vars="$ENV_VARS" \
            --service-account="$SERVICE_ACCOUNT" \
            --update-secrets=/usr/src/ntentan-api/secrets/firebase_cred.json=NTENTAN_FIREBASE_CREDENTIALS:latest \
            --timeout=900s \

          
           gcloud run services describe ntentan-api --project=furwoodd-775d1 --region=us-west1 --format=values(status.url)

        